## Random number in numpy.
---


### random — Generate pseudo-random numbers.

https://docs.python.org/3/library/random.html

***

In [1]:
# The random module from the standard library.
import random

#Numerical arrays, random numbers
import numpy as np

# Plots.
import matplotlib.pyplot as plt


In [2]:
# A "?" before a method produces help text for the method.
# This is a very handy tip!
?random.randint



Signature: random.randint(a, b)
Docstring:
Return random integer in range [a, b], including both end points.
        
File:      c:\users\administrator\anaconda3\lib\random.py
Type:      method

In [3]:
# Based on the above method help, we can generate a random integer 
# between 10 and 20 inclusive.
random.randint(10,20)

13

In [4]:
# Generate a list of random integers between 1 and 100.

L = [random.randint(1,10) for i in range (100)]

# Show L
#L
# Show first 10 elements of L
L[:10]

[2, 10, 4, 5, 7, 4, 3, 4, 1, 1]

In [5]:
# List of car makes.

makes=['Ford', 'Toyota', 'VW', 'Skoda']

In [6]:
# Select one at random.

random.choice(makes)

'Ford'

In [7]:
# Select ten random makes (with replacement).

random.choices(makes, k=10)

['Ford',
 'VW',
 'Toyota',
 'Toyota',
 'Skoda',
 'Ford',
 'Ford',
 'Toyota',
 'VW',
 'Toyota']

In [8]:
# First eight letters.

letters = ['A', 'B', 'C', 'D', 'E', 'F' , 'G', 'H']

In [9]:
# Shuufle them

random.shuffle(letters)

In [10]:
# Look at letters after shuffle.
letters

['E', 'G', 'H', 'D', 'C', 'F', 'B', 'A']

In [11]:
# Random selection without replacement.
random.sample(letters,k=5)

['C', 'B', 'F', 'G', 'A']

In [12]:
# random real (floating point) numbers [0.0, 1.0).

random.random()

0.8832974022077996

In [13]:
# Pick a random floating point number between 0 and 100 [0.0,100.0].
random.uniform(0.0,100.0)

49.525511807538656

## numpy

[numpy API Reference : Random sampling](https://numpy.org/doc/stable/reference/random/index.html)

https://numpy.org/doc/stable/reference/random/index.html

***

In [14]:
# Random number generator (RNG) for generating random numbers.
rng = np.random.default_rng()

In [15]:
# Generate random floats in the half-open interval [0.0, 1.0).
# Generate one random float uniformly distributed over the range [0, 1).
rng.random()  

0.6846353371578363

Generate numbers on standard Normal distribution.

The mean is 0.00 and standard deviation is 1.0.

The numbers genrated should be , on average, centered on 0.0.

More than 99% of teh numbers generated should be between -3.0 and 3.0 (in the interval (-3.0, 3.0)). 




In [16]:

# Generate an array of 10 numbers according to a unit Gaussian distribution.
rng.standard_normal(10)  

array([-0.1619709 ,  0.62992815, -0.50454259,  0.58171395,  1.33783633,
       -1.2000166 ,  1.8993407 , -0.75631332, -1.45090826,  0.02942354])

In [17]:
# Generate an array of 5 integers uniformly over the range [0, 10).
rng.integers(low=0, high=10, size=5)  

array([4, 5, 0, 3, 4], dtype=int64)

In [18]:
# Generate 15 integers between 10 (included) and 20 (excluded).
rng.integers(low=10, high=20, size=15)  

array([18, 13, 18, 10, 11, 18, 11, 13, 17, 19, 12, 15, 14, 10, 10],
      dtype=int64)

***

#### End